import { WidgetConfig } from "./types";

export const ADMIN_WIDGETS: WidgetConfig[] = [
  {
    id: "recent-activity",
    title: "Recent Activity",
    description: "Timeline of recent warehouse actions",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 0,
    defaultSize: "half",
  },
  {
    id: "quick-actions",
    title: "Quick Actions",
    description: "Shortcuts to common tasks",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 1,
    defaultSize: "half",
  },
  {
    id: "attention-required",
    title: "Attention Required",
    description: "Stale outbound and overdue inbound orders",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 2,
    defaultSize: "half",
  },
  {
    id: "low-stock-alerts",
    title: "Low Stock Alerts",
    description: "Items below reorder point",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 3,
    defaultSize: "half",
  },
  {
    id: "expected-arrivals",
    title: "Expected Arrivals",
    description: "Upcoming inbound shipments",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 4,
    defaultSize: "half",
  },
  {
    id: "orders-to-ship",
    title: "Orders to Ship",
    description: "Outbound orders ready for shipping",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 5,
    defaultSize: "half",
  },
  {
    id: "orders-summary",
    title: "Orders Summary",
    description: "Order pipeline progress bars",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 6,
    defaultSize: "half",
  },
  {
    id: "inventory-overview",
    title: "Inventory Overview",
    description: "High-level inventory stats",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 7,
    defaultSize: "half",
  },
  {
    id: "pending-returns",
    title: "Pending Returns",
    description: "Returns awaiting approval",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 8,
    defaultSize: "half",
  },
  {
    id: "unread-messages",
    title: "Unread Messages",
    description: "Messages needing attention",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 9,
    defaultSize: "half",
  },
  {
    id: "expiring-lots",
    title: "Expiring Lots",
    description: "Lots expiring within 30 days",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 10,
    defaultSize: "half",
  },
  {
    id: "inventory-aging",
    title: "Inventory Aging",
    description: "Donut chart of slow-moving inventory",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 11,
    defaultSize: "half",
  },
  {
    id: "order-velocity",
    title: "Order Velocity",
    description: "Weekly shipped vs received chart",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 12,
    defaultSize: "half",
  },
  {
    id: "outstanding-invoices",
    title: "Outstanding Invoices",
    description: "Unpaid invoice balance and counts",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 13,
    defaultSize: "half",
  },
];
