import { WidgetConfig } from "./types";

export const ADMIN_WIDGETS: WidgetConfig[] = [
  {
    id: "recent-activity",
    title: "Recent Activity",
    description: "Timeline of recent warehouse actions",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 0,
    defaultSize: "half",
    previewType: "timeline",
  },
  {
    id: "quick-actions",
    title: "Quick Actions",
    description: "Shortcuts to common tasks",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 1,
    defaultSize: "half",
    previewType: "action-grid",
  },
  {
    id: "attention-required",
    title: "Attention Required",
    description: "Stale outbound and overdue inbound orders",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 2,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "low-stock-alerts",
    title: "Low Stock Alerts",
    description: "Items below reorder point",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 3,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "expected-arrivals",
    title: "Expected Arrivals",
    description: "Upcoming inbound shipments",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 4,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "orders-to-ship",
    title: "Orders to Ship",
    description: "Outbound orders ready for shipping",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 5,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "orders-summary",
    title: "Orders Summary",
    description: "Order pipeline progress bars",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 6,
    defaultSize: "half",
    previewType: "progress-bars",
  },
  {
    id: "inventory-overview",
    title: "Inventory Overview",
    description: "High-level inventory stats",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 7,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "pending-returns",
    title: "Pending Returns",
    description: "Returns awaiting approval",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 8,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "unread-messages",
    title: "Unread Messages",
    description: "Messages needing attention",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 9,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "expiring-lots",
    title: "Expiring Lots",
    description: "Lots expiring within 30 days",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 10,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "inventory-aging",
    title: "Inventory Aging",
    description: "Donut chart of slow-moving inventory",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 11,
    defaultSize: "half",
    previewType: "donut",
  },
  {
    id: "order-velocity",
    title: "Order Velocity",
    description: "Weekly shipped vs received chart",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 12,
    defaultSize: "half",
    previewType: "bar-chart",
  },
  {
    id: "outstanding-invoices",
    title: "Outstanding Invoices",
    description: "Unpaid invoice balance and counts",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 13,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "fulfillment-funnel",
    title: "Fulfillment Funnel",
    description: "Order pipeline from pending to delivered",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 14,
    defaultSize: "half",
    previewType: "funnel",
  },
  {
    id: "inbound-outbound-flow",
    title: "Inbound vs Outbound",
    description: "30-day trend of units received vs shipped",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 15,
    defaultSize: "full",
    previewType: "line-chart",
  },
  {
    id: "inventory-value-treemap",
    title: "Inventory Value by Category",
    description: "Visual breakdown of inventory value across categories",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 16,
    defaultSize: "half",
    previewType: "treemap",
  },
  {
    id: "on-time-shipment",
    title: "On-Time Shipment Rate",
    description: "Weekly on-time delivery percentage trend",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 17,
    defaultSize: "half",
    previewType: "line-chart",
  },
  {
    id: "invoice-aging",
    title: "Invoice Aging",
    description: "Breakdown of outstanding invoices by age bucket",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 18,
    defaultSize: "half",
    previewType: "stacked-bar",
  },
  {
    id: "supplier-lead-times",
    title: "Supplier Lead Times",
    description: "Average days from PO to receipt by supplier",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 19,
    defaultSize: "half",
    previewType: "horizontal-bar",
  },
  {
    id: "return-rates",
    title: "Return Rates",
    description: "Product return rates as percentage of shipped units",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 20,
    defaultSize: "half",
    previewType: "horizontal-bar",
  },
  {
    id: "days-of-supply",
    title: "Days of Supply",
    description: "Projected days until stockout by product",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 21,
    defaultSize: "half",
    previewType: "horizontal-bar",
  },
  {
    id: "revenue-by-client",
    title: "Revenue by Client",
    description: "Invoice revenue breakdown by client",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 22,
    defaultSize: "half",
    previewType: "horizontal-bar",
  },
  // ── New widgets ──
  {
    id: "daily-throughput",
    title: "Daily Throughput",
    description: "Units picked, packed, and shipped per day over 14 days",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 23,
    defaultSize: "half",
    previewType: "bar-chart",
  },
  {
    id: "order-cycle-time",
    title: "Order Cycle Time",
    description: "Distribution of days from order to ship",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 24,
    defaultSize: "half",
    previewType: "bar-chart",
  },
  {
    id: "abc-analysis",
    title: "ABC Analysis",
    description: "Pareto chart of SKUs by cumulative inventory value",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 25,
    defaultSize: "half",
    previewType: "pareto",
  },
  {
    id: "inventory-turnover",
    title: "Inventory Turnover",
    description: "Turnover ratio by product category",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 26,
    defaultSize: "half",
    previewType: "horizontal-bar",
  },
  {
    id: "stock-level-heatmap",
    title: "Stock Level Heatmap",
    description: "Product vs location fill-level grid",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 27,
    defaultSize: "full",
    previewType: "heatmap",
  },
  {
    id: "reorder-proximity",
    title: "Reorder Proximity",
    description: "How close top products are to their reorder point",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 28,
    defaultSize: "half",
    previewType: "bullet",
  },
  {
    id: "inventory-accuracy",
    title: "Inventory Accuracy",
    description: "Cycle count accuracy trend over time",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 29,
    defaultSize: "half",
    previewType: "line-chart",
  },
  {
    id: "profit-margin-waterfall",
    title: "Profit Margin Waterfall",
    description: "Revenue to net profit breakdown step-by-step",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 30,
    defaultSize: "half",
    previewType: "waterfall",
  },
  {
    id: "monthly-revenue-trend",
    title: "Monthly Revenue Trend",
    description: "12-month invoice revenue area chart",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 31,
    defaultSize: "half",
    previewType: "area-chart",
  },
  {
    id: "storage-revenue-sqft",
    title: "Storage Revenue / Sq Ft",
    description: "Revenue per square foot by warehouse zone",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 32,
    defaultSize: "half",
    previewType: "horizontal-bar",
    comingSoon: true,
  },
  {
    id: "receiving-accuracy",
    title: "Receiving Accuracy",
    description: "Percentage of correctly received items by supplier",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 33,
    defaultSize: "half",
    previewType: "horizontal-bar",
  },
  {
    id: "inbound-forecast",
    title: "Inbound Forecast",
    description: "90-day calendar view of expected inbound shipments",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 34,
    defaultSize: "full",
    previewType: "calendar",
  },
  {
    id: "returns-by-reason",
    title: "Returns by Reason",
    description: "Donut breakdown of return reasons",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 35,
    defaultSize: "half",
    previewType: "donut",
  },
  {
    id: "damage-rate-trend",
    title: "Damage Rate Trend",
    description: "Monthly damage report count over 6 months",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 36,
    defaultSize: "half",
    previewType: "line-chart",
  },
  {
    id: "expiration-timeline",
    title: "Expiration Timeline",
    description: "Gantt-style view of upcoming lot expirations",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 37,
    defaultSize: "full",
    previewType: "gantt",
  },
  {
    id: "fefo-compliance",
    title: "FEFO Compliance",
    description: "First-expired-first-out compliance gauge",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 38,
    defaultSize: "half",
    previewType: "gauge",
    comingSoon: true,
  },
];
