import { WidgetConfig } from "./types";

export const PORTAL_WIDGETS: WidgetConfig[] = [
  {
    id: "unread-messages",
    title: "Unread Messages",
    description: "Messages needing your attention",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 0,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "open-returns",
    title: "Open Returns",
    description: "Returns currently being processed",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 1,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "profitability",
    title: "This Month's Profitability",
    description: "Net profit and margin for the current month",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 2,
    defaultSize: "half",
    previewType: "count-badge",
  },
  {
    id: "recent-orders",
    title: "Recent Orders",
    description: "Your latest outbound orders",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 3,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "recent-arrivals",
    title: "Recent Arrivals",
    description: "Recently received inbound shipments",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 4,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "active-orders",
    title: "Active Orders",
    description: "Orders in progress with tracking",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 5,
    defaultSize: "half",
    previewType: "list",
  },
  {
    id: "quick-actions",
    title: "Quick Actions",
    description: "Shortcuts to common portal tasks",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 6,
    defaultSize: "half",
    previewType: "action-grid",
  },
  // ── New portal widgets ──
  {
    id: "inventory-value-over-time",
    title: "Inventory Value Over Time",
    description: "Track how your inventory value changes monthly",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 7,
    defaultSize: "half",
    previewType: "area-chart",
  },
  {
    id: "order-fulfillment-speed",
    title: "Order Fulfillment Speed",
    description: "Average days from order to delivery",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 8,
    defaultSize: "half",
    previewType: "line-chart",
  },
  {
    id: "spending-breakdown",
    title: "Spending Breakdown",
    description: "Where your warehousing costs go",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 9,
    defaultSize: "half",
    previewType: "donut",
  },
  {
    id: "product-performance",
    title: "Product Performance",
    description: "Units sold vs profit margin scatter plot",
    category: "analytics",
    defaultEnabled: false,
    defaultOrder: 10,
    defaultSize: "half",
    previewType: "scatter",
  },
  {
    id: "stock-projection",
    title: "Stock Projection",
    description: "Predicted stock levels for next 30 days",
    category: "operational",
    defaultEnabled: false,
    defaultOrder: 11,
    defaultSize: "half",
    previewType: "line-chart",
  },
];
