import { WidgetConfig } from "./types";

export const PORTAL_WIDGETS: WidgetConfig[] = [
  {
    id: "unread-messages",
    title: "Unread Messages",
    description: "Messages needing your attention",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 0,
    defaultSize: "half",
  },
  {
    id: "open-returns",
    title: "Open Returns",
    description: "Returns currently being processed",
    category: "communication",
    defaultEnabled: true,
    defaultOrder: 1,
    defaultSize: "half",
  },
  {
    id: "profitability",
    title: "This Month's Profitability",
    description: "Net profit and margin for the current month",
    category: "analytics",
    defaultEnabled: true,
    defaultOrder: 2,
    defaultSize: "half",
  },
  {
    id: "recent-orders",
    title: "Recent Orders",
    description: "Your latest outbound orders",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 3,
    defaultSize: "half",
  },
  {
    id: "recent-arrivals",
    title: "Recent Arrivals",
    description: "Recently received inbound shipments",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 4,
    defaultSize: "half",
  },
  {
    id: "active-orders",
    title: "Active Orders",
    description: "Orders in progress with tracking",
    category: "operational",
    defaultEnabled: true,
    defaultOrder: 5,
    defaultSize: "half",
  },
  {
    id: "quick-actions",
    title: "Quick Actions",
    description: "Shortcuts to common portal tasks",
    category: "core",
    defaultEnabled: true,
    defaultOrder: 6,
    defaultSize: "half",
  },
];
